# Generated by Django 4.1.1 on 2023-06-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('post', models.CharField(max_length=25)),
                ('phone_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/%Y')),
            ],
        ),
    ]
