# Generated by Django 4.1.4 on 2023-06-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
