# Generated by Django 4.2.2 on 2023-06-14 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_remove_product_account'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_app.product'),
        ),
    ]
