# Generated by Django 4.2.2 on 2023-06-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_remove_product_account'),
        ('user_app', '0002_account_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='product',
        ),
        migrations.AddField(
            model_name='account',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='menu_app.product'),
        ),
    ]
