# Generated by Django 4.2.2 on 2023-06-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_remove_product_account'),
        ('user_app', '0003_remove_account_product_account_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='product',
            field=models.ManyToManyField(to='menu_app.product'),
        ),
    ]
