# Generated by Django 4.1.4 on 2023-06-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_account_product_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
